version: "3"

tasks:
  setup:
    desc: Initialize development setup
    deps:
      - setup-poetry
      - setup-pnpm
      - setup-kind

  setup-pnpm:
    desc: Will clean the repo node_modules and configure pnpm using corepack
    cmds:
      - find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
      - COREPACK_ENABLE_STRICT=0 && corepack enable && corepack prepare pnpm@9.9.0 --activate
      - pnpm i

  setup-poetry:
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  setup-kind:
    desc: Sets up kinds cluster
    cmds:
      - .tools/delete-cluster.sh
      - .tools/create-cluster.sh
